[general]
import = [
  "~/.config/alacritty/gruvbox.toml"
]

[font]
size = 16.0

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = true

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001b[47;5u" },
]
